### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-jquery-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://keen-potato.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/jquery-intro/1) criteria:
- [x] [This HTML file](https://gist.github.com/chrisvfritz/6ff8b4a898468bdf6d2c) is used to build off (you may change any part of it)
- [x] Players have some way to add either an X or O to each square (apart from event handlers, you may also find [the `text` function](http://api.jquery.com/text/#text2) useful)
- [x] Squares with Xs and squares with Os have different background colors
- [x] The reset button clears Xs and Os from every square
- [ ](optional) Win conditions do _NOT_ have to be detected and reported, but you have the knowledge to accomplish this if you'd like a challenge

**Comment by chrisvfritz** [comment]
Looks great! :shipit: I only have a tiny refactor to offer that would speed up the code by avoid creating so many jQuery objects. You probably won't notice any speed improvement for this example, but as you start building larger applications, it really does make a difference. :smiley: 

``` js
// Since we were doing creating a jQuery object twice,
// I moved it to a variable here to make our code faster.
// I also "scoped" the td to only target td elements 
// inside of a gameboard. This makes our code more 
// "future-proof" - meaning it's more likely to still 
// work without side effects, even after adding another 
// unrelated table in the future.
var $gameCells = $('.game-board td')

$gameCells.on('click', function(){
  // I did the same thing assigning a variable to the 
  // jQuery object, so that the JavaScript woud only
  // have to scan the page for it once, rather than
  // more than half a dozen times.
  var $this = $(this)

  if (!$this.hasClass('x') && !$this.hasClass('o')) {
    $this
      .text('X')
      .addClass('x')
  }
  else if ($this.hasClass('x')) {
    $this
      .text('O')
      .addClass('o')
      .removeClass('x')
  }
  else if ($this.hasClass('o')) {
    $this
      .text('')
      .removeClass('x o')
  }
})
$('#reset-button').on('click', function(){
  $gameCells
    .removeClass('x o')
    .text('')
})
```
